name: remote ssh command
on: 
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key a
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd OpaFrutas
          sudo git pull origin main
          sudo cp index.html /var/www/html/index.nginx-debian.html
          sudo systemctl restart nginx
